CREATE TABLE IF NOT EXISTS plano (
id_plan INT NOT NULL AUTO_INCREMENT,
nom_plan VARCHAR(255) NOT NULL,
temp_ise_plan BIGINT(20) NOT NULL,
tax_plan FLOAT(5) NOT NULL DEFAULT 0.1,
CONSTRAINT pk_plano PRIMARY KEY (id_plan)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS valor_por_minuto(
id_val_min INT NOT NULL AUTO_INCREMENT,
ddd_ori_val_min VARCHAR(20) NOT NULL,
ddd_des_val_min VARCHAR(20) NOT NULL,
val_min_val_min  FLOAT(5) NOT NULL,
CONSTRAINT pk_valor_por_minuto PRIMARY KEY (id_val_min)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;